version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: baytalmahashy-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/baytalmahashy
    networks:
      - baytalmahashy-network

  mongo:
    image: mongo:5.0
    container_name: baytalmahashy-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - baytalmahashy-network

  mongo-express:
    image: mongo-express
    container_name: baytalmahashy-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    depends_on:
      - mongo
    networks:
      - baytalmahashy-network

networks:
  baytalmahashy-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local